# Introdução

Numpy é uma biblioteca numérica do Python. Muito poderosa para data Science e computação científica.

#### Instalando o Numpy

A primeira coisa que é preciso fazer é a instalação da biblioteca. Para isso utilizamos o comando: **pip install numpy**.

#### Importação

Feita a instalção, basta importar a biblioteca.

In [1]:
import numpy as np

#### Criando um Array

## O que é um array?

Podemos definir um array como uma sequência ordenada de números que podem ter n dimenções. 

Tipos de arrays:

0-D array -> Caso a dimenção seja 0, temos apenas um escalar, um número.

1-D array-> Possui apenas uma dimensão. Será comumente chamado de <b> vetor ou vector </b> <br>

2-D array -> Possui 2 dimensões. Será comumente chamado de <b> matriz ou matrix</b> <br>

3-D ou Mais array -> Possui 3 ou mais dimensões. Será comumente chamado de <b>tensor</b> 

**para criar uma array, utilizamos o comando np.array( )**

In [2]:
array_0d = np.array(4)
print(array_0d)

4


In [3]:
array_1d= np.array([1, 2, 3, 4, 5])
print(array_1d)

[1 2 3 4 5]


In [4]:
array_2d = np.array([[1,2],[3,4],[5,6]])
print(array_2d)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Arrays especiais?

O que quero dizer é que existem vetores, matrizes e tensores que possuem características especiais e damos nome para elas. Como o numpy reconhece essas características, ele ja criou métodos específicos para faciliar a nossa vida, como vermos a seguir.

### np.zeros( )

O primeiro tipo é para criar um array onde todos as entradas são 0. 

Podemos definir qual o tipo da dimensão do array da seguinte maneira:

np.zeros(5), vetor.

np.zeros((3,4)), matriz.

np.zeros((3,2,5)), tensor.



In [6]:
zeros_1d = np.zeros(3)
print(zeros_1d)

[0. 0. 0.]


In [7]:
zeros_2d = np.zeros((3,3))
print(zeros_2d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
zeros_3d = np.zeros((4,2,2))
print(zeros_3d)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


### np.ones( )

O primeiro tipo é para criar um array onde todos as entradas são 1. 

Mesma ideia de criação do np.zeros( ).

In [9]:
ones_1d = np.ones(5)
print(ones_1d)

[1. 1. 1. 1. 1.]


In [10]:
ones_2d = np.ones((3,4))
print(ones_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
ones_3d = np.ones((2,1,2))
print(ones_3d)

[[[1. 1.]]

 [[1. 1.]]]


### np.random.rand( ) 

In [41]:
np.random.rand(4,2)

array([[0.39698707, 0.79029621],
       [0.67629182, 0.87783683],
       [0.58903497, 0.20037633],
       [0.81705864, 0.55664768]])

### np.random.randint( )

In [43]:
np.random.randint(-4,8, size=(3,3))

array([[ 4,  5,  6],
       [ 6, -1,  6],
       [-3, -1, -2]])

### np.identity( ) ou np.eye( )

In [39]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.empty( )

Fala empty, que é vaizo em inglês, mas na verdade ele cria um vetor, matriz ou tensor com nenhuma entrada vazia e com números aletórios e não inicializa as entradas

A criação funciona da mesma forma que a anterior.



In [12]:
empty_1d = np.empty(4)
print(empty_1d)

[1. 1. 1. 1.]


In [13]:
empty_2d = np.empty((4,5))
print(empty_2d)

[[4.45055939e-308 1.60219035e-306 1.37969994e-306 4.45057637e-308
  1.86921551e-306]
 [4.45057637e-308 4.45061032e-308 1.51320097e-306 1.37961709e-306
  1.37969994e-306]
 [8.90195230e-307 9.34609110e-307 1.37961302e-306 1.86920872e-306
  4.45055939e-308]
 [8.90098127e-307 7.56603881e-307 1.78020848e-306 4.99006302e-322
  1.29062229e-306]]


In [14]:
empty_3d = np.empty((1,2,3))
print(empty_3d)

[[[0. 0. 0.]
  [0. 0. 0.]]]


## Criação de array de forma "inteligente"

Quando queremos criar um array onde as entradas estão igualmente espaçadas, podemos utilizar dois métodos diferentes, o np.arange( ) e o np.linspace( ).

### np.arange( )

O arange cria um vetor onde o espaçamento padrão e valor incial é 1 e 0, respectivamente, o terceiro parâmetro é o salto, step, que indica o pulo entre os valores.

Caso queira apenas indicar a quantidade de valores, apenas digite um valor. Caso queira indicar o star, stop e step, indique os 3, nessa sequência. 

In [15]:
zero_dez = np.arange(10)
print(zero_dez)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
pula_cinco = np.arange(5,100,5)
print(pula_cinco)

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


### np.linspace( )

O linspace funciona de forma similar, mas indica a quantidade de elementos que o array vai ter. Então ele divide o tamanho do array pela quantidade que vc indica e almenta elemento a elemento essa quantidade.

O primeiro argumento é o star, segundo é o stop e o terceiro é a quantidade de elementos.

Possui ainda dois argumentos opcionais: endpoint = False, retstep = True. O primeiro vc escolhe se o valor finai inclue ou não no vetor; O segundo vc escolhe se ele quer mostrar ou não a quantidade acrecida para cada valor. 


In [21]:
lin = np.linspace(1,100, 15)
print(lin)

[  1.           8.07142857  15.14285714  22.21428571  29.28571429
  36.35714286  43.42857143  50.5         57.57142857  64.64285714
  71.71428571  78.78571429  85.85714286  92.92857143 100.        ]


In [22]:
array_linear = np.linspace(0, 100 , 20, endpoint = False, retstep = True)
print(array_linear)

(array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60.,
       65., 70., 75., 80., 85., 90., 95.]), 5.0)


## Alguns métodos úteis

In [28]:
array = np.array([3,4,5])
print(array)

[3 4 5]


#### array.shape 

In [29]:
print(array.shape)

(3,)


#### array.size

In [30]:
print(array.size)

3


#### array.ndim

In [31]:
print(array.ndim)

1


#### array.max

In [33]:
print(array.max())

5


#### array.min

In [34]:
print(array.min())

3


#### array.mean

In [35]:
print(array.mean())

4.0


#### array.sum

In [36]:
print(array.sum())

12


### Criação de dados aleatório

In [37]:
from numpy.random import default_rng

In [38]:
rng= default_rng()
aleatorio = rng.integers(10, size=(2,4))
print(aleatorio)

[[2 1 3 0]
 [0 6 6 1]]
