# Introdução

Numpy é uma biblioteca numérica do Python. Muito poderosa para data Science e computação científica.

#### Instalando o Numpy

A primeira coisa que é preciso fazer é a instalação da biblioteca. Para isso utilizamos o comando: **pip install numpy**.

#### Importação

Feita a instalção, basta importar a biblioteca.

In [2]:
import numpy as np

In [9]:
x = np.ones([5,5])
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
x[1:4,1:4] = np.zeros([3,3])
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
x[2,2] = 9
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])